import { InventoryItem } from './types';

export const INITIAL_INVENTORY: Omit<InventoryItem, 'id' | 'lastUpdated'>[] = [
  // Sauces
  { name: 'White Choco', emoji: '🤍', category: 'Sauces', quantity: '1', unit: 'pcs', lowStockThreshold: 1 },
  { name: 'Dark Choco', emoji: '🤎', category: 'Sauces', quantity: '0', unit: 'pcs', lowStockThreshold: 1 },
  { name: 'Caramel', emoji: '🍮', category: 'Sauces', quantity: '1', unit: 'pcs', lowStockThreshold: 1 },
  { name: 'Butterscotch', emoji: '🍬', category: 'Sauces', quantity: '2', unit: 'pcs', lowStockThreshold: 1 },

  // Syrups
  { name: 'Choco Macadamia', emoji: '🌰', category: 'Syrups', quantity: '2', unit: 'pcs', lowStockThreshold: 1 },
  { name: 'English Toffee (Torani)', emoji: '🍬', category: 'Syrups', quantity: '0', unit: 'pcs', lowStockThreshold: 1 },
  { name: 'English Toffee (Da Vinci)', emoji: '🍬', category: 'Syrups', quantity: '2', unit: 'pcs', lowStockThreshold: 1 },
  { name: 'Hazelnut (Da Vinci)', emoji: '🥜', category: 'Syrups', quantity: '4', unit: 'pcs', lowStockThreshold: 1 },
  { name: 'French Vanilla', emoji: '🍦', category: 'Syrups', quantity: '3', unit: 'pcs', lowStockThreshold: 1 },
  { name: 'Butterscotch', emoji: '🧈', category: 'Syrups', quantity: '1', unit: 'pcs', lowStockThreshold: 1 },
  { name: 'Hazelnut (Torani)', emoji: '🥜', category: 'Syrups', quantity: '0', unit: 'pcs', lowStockThreshold: 1 },
  { name: 'Macadamia Nut', emoji: '🌰', category: 'Syrups', quantity: '4', unit: 'pcs', lowStockThreshold: 1 },
  { name: 'Caramel (Torani)', emoji: '🍯', category: 'Syrups', quantity: '0', unit: 'pcs', lowStockThreshold: 1 },
  { name: 'Caramel (Da Vinci)', emoji: '🍯', category: 'Syrups', quantity: '3', unit: 'pcs', lowStockThreshold: 1 },
  { name: 'Cheesecake', emoji: '🍰', category: 'Syrups', quantity: '3', unit: 'pcs', lowStockThreshold: 1 },

  // Others
  { name: 'Strawberry Jam', emoji: '🍓', category: 'Others', quantity: '3', unit: 'jars', lowStockThreshold: 1 },
  { name: 'Matcha', emoji: '🍵', category: 'Others', quantity: 'Half', unit: 'canister', lowStockThreshold: 1 },
  { name: 'Coffee Beans', emoji: '🫘', category: 'Others', quantity: '1', unit: 'pcs', lowStockThreshold: 1 },
  { name: 'Nutella', emoji: '🍫', category: 'Others', quantity: '4', unit: 'jars', lowStockThreshold: 1 },
  { name: 'Thin Straws', emoji: '🥤', category: 'Others', quantity: '6', unit: 'packs', lowStockThreshold: 2 },
  { name: 'Jumbo Straws', emoji: '🥤', category: 'Others', quantity: '8', unit: 'packs', lowStockThreshold: 2 },
  { name: 'Whip Cream', emoji: '🍦', category: 'Others', quantity: '3', unit: 'pcs', lowStockThreshold: 1 },
  { name: 'Cream Charger', emoji: '💨', category: 'Others', quantity: '2 boxes + 2 pcs', unit: '', lowStockThreshold: 1 },

  // Lazada Supplies
  { name: 'Rice', emoji: '🍚', category: 'Lazada Supplies', quantity: '0', unit: 'pcs', lowStockThreshold: 1 },
  { name: 'Fries', emoji: '🍟', category: 'Lazada Supplies', quantity: '0', unit: 'pcs', lowStockThreshold: 1 },
  { name: 'Slider/Decker', emoji: '🍔', category: 'Lazada Supplies', quantity: '1', unit: 'pack', lowStockThreshold: 1 },
  { name: 'Egg drop sheet', emoji: '🍳', category: 'Lazada Supplies', quantity: '2', unit: 'packs', lowStockThreshold: 1 },
  { name: 'Egg drop paper box', emoji: '📦', category: 'Lazada Supplies', quantity: '4', unit: 'packs', lowStockThreshold: 1 },
  { name: 'Fries clamshells', emoji: '🍟', category: 'Lazada Supplies', quantity: '1', unit: 'pack', lowStockThreshold: 1 },
  { name: 'Bag A', emoji: '🛍️', category: 'Lazada Supplies', quantity: '2', unit: 'packs', lowStockThreshold: 1 },
  { name: 'Bag B', emoji: '🛍️', category: 'Lazada Supplies', quantity: '2', unit: 'packs', lowStockThreshold: 1 },
  { name: 'Bag C', emoji: '🛍️', category: 'Lazada Supplies', quantity: '2', unit: 'packs', lowStockThreshold: 1 },
  { name: 'Single Drinks Plastic', emoji: '🥤', category: 'Lazada Supplies', quantity: '0', unit: 'pcs', lowStockThreshold: 1 },
  { name: 'Double Drinks Plastic', emoji: '🥤', category: 'Lazada Supplies', quantity: '2', unit: 'packs', lowStockThreshold: 1 },
  { name: 'Decker Box', emoji: '📦', category: 'Lazada Supplies', quantity: '50', unit: 'pcs (est.) with lids', lowStockThreshold: 10 },
  { name: 'Eggdrop plastic', emoji: '🍳', category: 'Lazada Supplies', quantity: '3', unit: 'packs', lowStockThreshold: 1 },
  { name: 'Spill proof paper', emoji: '📄', category: 'Lazada Supplies', quantity: '2', unit: 'sets', lowStockThreshold: 1 },
  { name: 'Parsley', emoji: '🌿', category: 'Lazada Supplies', quantity: '½', unit: 'pack', lowStockThreshold: 0.5 },
  { name: 'Paprika', emoji: '🌶️', category: 'Lazada Supplies', quantity: '½', unit: 'pack', lowStockThreshold: 0.5 },
  { name: 'Onion Powder', emoji: '🧅', category: 'Lazada Supplies', quantity: '½', unit: 'pack', lowStockThreshold: 0.5 },
  { name: 'Garlic Powder', emoji: '🧄', category: 'Lazada Supplies', quantity: '½', unit: 'pack', lowStockThreshold: 0.5 },
  { name: 'POS roll', emoji: '🧾', category: 'Lazada Supplies', quantity: '9', unit: 'rolls', lowStockThreshold: 3 },

  // S&R Supplies
  { name: 'Lettuce', emoji: '🥬', category: 'S&R Supplies', quantity: '4½', unit: 'bags', lowStockThreshold: 1 },
  { name: 'Cabbage', emoji: '🥬', category: 'S&R Supplies', quantity: '3', unit: 'pcs', lowStockThreshold: 1 },
  { name: 'Pipino', emoji: '🥒', category: 'S&R Supplies', quantity: '3', unit: 'pcs', lowStockThreshold: 1 },
  { name: 'Egg', emoji: '🥚', category: 'S&R Supplies', quantity: '12', unit: 'pcs', lowStockThreshold: 6 },
  { name: 'Breast fillet', emoji: '🍗', category: 'S&R Supplies', quantity: '2', unit: 'tubs (frozen)', lowStockThreshold: 1 },
  { name: 'Fresh milk', emoji: '🥛', category: 'S&R Supplies', quantity: '1 box + 9 cartons', unit: '', lowStockThreshold: 5 },
  { name: 'Fries', emoji: '🍟', category: 'S&R Supplies', quantity: '5', unit: 'bags', lowStockThreshold: 2 },
  { name: 'Nutella', emoji: '🍫', category: 'S&R Supplies', quantity: '7', unit: 'glass jars', lowStockThreshold: 2 },
  { name: 'Biscoff spread', emoji: '🍪', category: 'S&R Supplies', quantity: '1', unit: 'big jar', lowStockThreshold: 1 },
  { name: 'Black tub', emoji: '🍱', category: 'S&R Supplies', quantity: '1', unit: 'pack', lowStockThreshold: 1 },
  { name: '6pcs container', emoji: '🍱', category: 'S&R Supplies', quantity: '1', unit: 'pack', lowStockThreshold: 1 },
  { name: '4 pcs clam', emoji: '🍱', category: 'S&R Supplies', quantity: '0', unit: 'pcs', lowStockThreshold: 1 },
  { name: 'Gloves', emoji: '🧤', category: 'S&R Supplies', quantity: '2', unit: 'boxes', lowStockThreshold: 1 },
  { name: 'Spoon', emoji: '🥄', category: 'S&R Supplies', quantity: '1', unit: 'box', lowStockThreshold: 1 },
  { name: 'Fork', emoji: '🍴', category: 'S&R Supplies', quantity: '1', unit: 'box', lowStockThreshold: 1 },
  { name: '1oz Cup', emoji: '🥤', category: 'S&R Supplies', quantity: '5', unit: 'packs', lowStockThreshold: 2 },
  { name: '8oz Cup', emoji: '🥤', category: 'S&R Supplies', quantity: '1', unit: 'bag', lowStockThreshold: 1 },
  { name: 'Dining tissue', emoji: '🧻', category: 'S&R Supplies', quantity: '1', unit: 'bag', lowStockThreshold: 1 },
  { name: 'Japanese Mayo', emoji: '🧴', category: 'S&R Supplies', quantity: '3', unit: 'pcs', lowStockThreshold: 1 },
  { name: 'Sriracha', emoji: '🌶️', category: 'S&R Supplies', quantity: '3', unit: 'pcs', lowStockThreshold: 1 },
  { name: 'Mustard', emoji: '🧴', category: 'S&R Supplies', quantity: '0', unit: 'pcs', lowStockThreshold: 1 },
  { name: 'Heinz', emoji: '🍅', category: 'S&R Supplies', quantity: '1¾', unit: 'gallons', lowStockThreshold: 0.5 },
];
